import type { AssetSeed } from "./asset-universe.builders";
import { yahoo } from "./asset-universe.builders";

export const commodityAssets: AssetSeed[] = [
  yahoo("cmd-gold", "GC=F", "COMEX 黄金", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-silver", "SI=F", "COMEX 白银", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-copper", "HG=F", "COMEX 铜", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["工业金属"]),
  yahoo("cmd-platinum", "PL=F", "NYMEX 铂金", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-palladium", "PA=F", "NYMEX 钯金", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-wti", "CL=F", "WTI 原油", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-brent", "BZ=F", "Brent 原油", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-gas", "NG=F", "天然气", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-corn", "ZC=F", "CBOT 玉米", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-wheat", "ZW=F", "CBOT 小麦", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-soybean", "ZS=F", "CBOT 大豆", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-coffee", "KC=F", "ICE 咖啡", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-sugar", "SB=F", "ICE 原糖", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-cotton", "CT=F", "ICE 棉花", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-cocoa", "CC=F", "ICE 可可", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-orange-juice", "OJ=F", "ICE 橙汁", "commodity", "商品", "ICE", "USX", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-lumber", "LBR=F", "CME 木材", "commodity", "商品", "CME", "USD", "market-commodity", "instrument", ["木材", "周期"]),
  yahoo("cmd-oats", "ZO=F", "CBOT 燕麦", "commodity", "商品", "CBOT", "USX", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-rough-rice", "ZR=F", "CBOT 糙米", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-live-cattle", "LE=F", "CME 活牛", "commodity", "商品", "CME", "USD", "market-commodity", "instrument", ["牲畜"]),
  yahoo("cmd-feeder-cattle", "GF=F", "CME 饲牛", "commodity", "商品", "CME", "USX", "market-commodity", "instrument", ["牲畜"]),
  yahoo("cmd-lean-hogs", "HE=F", "CME 瘦猪肉", "commodity", "商品", "CME", "USD", "market-commodity", "instrument", ["牲畜"]),
  yahoo("cmd-rbob", "RB=F", "NYMEX RBOB 汽油", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源", "汽油"]),
  yahoo("cmd-heating-oil", "HO=F", "NYMEX 取暖油", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源", "燃油"]),
  yahoo("cmd-micro-gold", "MGC=F", "COMEX 微型黄金", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["贵金属", "黄金"]),
  yahoo("cmd-mini-copper", "QC=F", "COMEX 迷你铜", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["工业金属", "铜"]),
  yahoo("cmd-aluminum", "ALI=F", "COMEX 铝", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["工业金属", "铝"]),
  yahoo("fund-gld", "GLD", "SPDR 黄金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-iau", "IAU", "iShares 黄金信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-gldm", "GLDM", "SPDR Mini 黄金信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-slv", "SLV", "iShares 白银信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "白银"]),
  yahoo("fund-pplt", "PPLT", "abrdn 铂金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "铂金"]),
  yahoo("fund-pall", "PALL", "abrdn 钯金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "钯金"]),
  yahoo("fund-cper", "CPER", "United States 铜指数基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "工业金属", "铜"]),
  yahoo("fund-uso", "USO", "United States Oil Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "原油"]),
  yahoo("fund-ung", "UNG", "United States Natural Gas Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "天然气"]),
  yahoo("fund-dba", "DBA", "Invesco 农产品基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "农产品", "大宗商品"]),
  yahoo("fund-corn", "CORN", "Teucrium 玉米基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农产品", "玉米"]),
  yahoo("fund-weat", "WEAT", "Teucrium 小麦基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农产品", "小麦"]),
  yahoo("fund-soyb", "SOYB", "Teucrium 大豆基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农产品", "大豆"]),
  yahoo("fund-cane", "CANE", "Teucrium 糖基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "软商品", "糖"]),
  yahoo("fund-dbc", "DBC", "Invesco 综合商品指数基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "综合商品"]),
  yahoo("fund-pdbc", "PDBC", "Invesco 优化商品策略 ETF", "fund", "商品", "Nasdaq", "USD", "market-commodity-fund", "theme-basket", ["ETF", "综合商品"]),
  yahoo("fund-dbb", "DBB", "Invesco 基本金属基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "工业金属", "综合商品"]),
  yahoo("fund-dbp", "DBP", "Invesco 贵金属基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "贵金属", "综合商品"]),
  yahoo("fund-gsg", "GSG", "iShares GSCI 商品基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "综合商品"]),
  yahoo("fund-gdx", "GDX", "VanEck 黄金矿商 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "贵金属", "黄金矿商"]),
  yahoo("fund-gdxj", "GDXJ", "VanEck 小型黄金矿商 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "贵金属", "黄金矿商"]),
  yahoo("fund-sil", "SIL", "Global X 白银矿商 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "贵金属", "白银矿商"]),
  yahoo("fund-silj", "SILJ", "小型白银矿商 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "贵金属", "白银矿商"]),
  yahoo("fund-copx", "COPX", "Global X 铜矿 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "铜", "工业金属"]),
  yahoo("fund-pick", "PICK", "全球金属矿业 ETF", "fund", "商品", "Cboe", "USD", "market-commodity-fund", "theme-basket", ["ETF", "工业金属", "矿业"]),
  yahoo("fund-slx", "SLX", "VanEck 钢铁 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "钢铁", "工业金属"]),
  yahoo("fund-ura", "URA", "Global X 铀矿 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "铀", "核能", "能源"]),
  yahoo("fund-urnm", "URNM", "Sprott 铀矿 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "铀", "核能", "能源"]),
  yahoo("fund-nlr", "NLR", "VanEck 核能 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "核能", "能源"]),
  yahoo("fund-lit", "LIT", "Global X 锂电池 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "锂", "电池金属", "新能源"]),
  yahoo("fund-remx", "REMX", "VanEck 稀土战略金属 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "稀土", "工业金属", "战略金属"]),
  yahoo("fund-wood", "WOOD", "iShares 全球木材林业 ETF", "fund", "商品", "Nasdaq", "USD", "market-commodity-fund", "theme-basket", ["ETF", "木材", "林业", "周期"]),
  yahoo("fund-krbn", "KRBN", "KraneShares 全球碳信用 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "碳信用", "能源转型"]),
  yahoo("fund-bdry", "BDRY", "Breakwave 干散货运价 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "运价", "航运", "周期"]),
  yahoo("fund-bno", "BNO", "United States Brent Oil Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "原油"]),
  yahoo("fund-dbo", "DBO", "Invesco 原油基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "原油"]),
  yahoo("fund-dbe", "DBE", "Invesco 能源基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "能源", "综合商品"]),
  yahoo("fund-uga", "UGA", "United States Gasoline Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "汽油"]),
  yahoo("fund-unl", "UNL", "United States 12 Month Natural Gas Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "天然气"]),
  yahoo("fund-moo", "MOO", "VanEck 农业企业 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "农产品", "农业"]),
  yahoo("fund-xme", "XME", "SPDR 金属矿业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["ETF", "金属矿业", "周期"]),
  yahoo("fund-xop", "XOP", "SPDR 油气勘探 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["ETF", "油气", "能源"]),
  yahoo("fund-soxx", "SOXX", "iShares 半导体 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "sector-index", ["ETF", "半导体", "科技"]),
  yahoo("fund-smh", "SMH", "VanEck 半导体 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "sector-index", ["ETF", "半导体", "科技"]),
];
