import type { AssetSeed } from "./asset-universe.builders";
import { yahoo } from "./asset-universe.builders";

export const macroAssets: AssetSeed[] = [
  yahoo("rate-tlt", "TLT", "20Y+ 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("rate-ief", "IEF", "7-10Y 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("rate-shy", "SHY", "1-3Y 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("rate-agg", "AGG", "美国综合债券 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF", "综合债"]),
  yahoo("rate-bnd", "BND", "Vanguard 总债券市场 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "ETF", "综合债"]),
  yahoo("rate-hyg", "HYG", "高收益债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "信用债", "高收益"]),
  yahoo("rate-lqd", "LQD", "投资级公司债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "信用债", "投资级"]),
  yahoo("rate-emb", "EMB", "新兴市场美元债 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "新兴市场", "美元债"]),
  yahoo("rate-mub", "MUB", "美国市政债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "市政债"]),
  yahoo("rate-tip", "TIP", "通胀保值债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "通胀"]),
  yahoo("rate-vtip", "VTIP", "短期通胀保值债 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "通胀", "短债"]),
  yahoo("rate-bil", "BIL", "1-3 月美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "现金管理", "短债"]),
  yahoo("rate-sgov", "SGOV", "0-3 月美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "现金管理", "短债"]),
  yahoo("rate-shv", "SHV", "短期美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "现金管理", "短债"]),
  yahoo("rate-tlh", "TLH", "10-20Y 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "长债"]),
  yahoo("rate-scho", "SCHO", "短期美国国债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "短债"]),
  yahoo("rate-vcit", "VCIT", "中期公司债 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "信用债", "投资级"]),
  yahoo("rate-vcsh", "VCSH", "短期公司债 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "信用债", "短债"]),
  yahoo("rate-bndx", "BNDX", "国际债券 ETF", "fund", "债券", "Nasdaq", "USD", "market-rates", "instrument", ["债券", "国际债"]),
  yahoo("macro-tnx", "^TNX", "美国 10Y 利率", "macro", "宏观", "Yahoo", "%", "market-macro", "macro-indicator", ["利率"]),
  yahoo("macro-vix", "^VIX", "VIX 波动率指数", "macro", "宏观", "CBOE", "USD", "market-macro", "macro-indicator", ["风险"]),
  yahoo("fx-dxy", "DX-Y.NYB", "美元指数", "macro", "外汇", "ICE", "USD", "market-fx", "instrument", ["美元"]),
  yahoo("fx-eurusd", "EURUSD=X", "欧元兑美元", "macro", "外汇", "Yahoo", "USD", "market-fx", "instrument", ["外汇"]),
  yahoo("fx-usdjpy", "JPY=X", "美元兑日元", "macro", "外汇", "Yahoo", "JPY", "market-fx", "instrument", ["外汇"]),
  yahoo("fx-usdcny", "USDCNY=X", "美元兑人民币", "macro", "外汇", "Yahoo", "CNY", "market-fx", "instrument", ["外汇"]),
  yahoo("fx-uup", "UUP", "美元多头 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "美元"]),
  yahoo("fx-udn", "UDN", "美元空头 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "美元"]),
  yahoo("fx-usdu", "USDU", "WisdomTree 美元多头基金", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "美元"]),
  yahoo("fx-fxe", "FXE", "欧元 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "欧元"]),
  yahoo("fx-fxy", "FXY", "日元 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "日元"]),
  yahoo("fx-fxb", "FXB", "英镑 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "英镑"]),
  yahoo("fx-fxc", "FXC", "加元 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "加元"]),
  yahoo("fx-fxa", "FXA", "澳元 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "澳元"]),
  yahoo("fx-fxf", "FXF", "瑞郎 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "瑞郎"]),
  yahoo("fx-cew", "CEW", "新兴市场货币 ETF", "fund", "外汇", "NYSE Arca", "USD", "market-fx", "instrument", ["外汇", "新兴市场"]),
];
