import type { AssetSeed } from "./asset-universe.builders";
import { yahoo } from "./asset-universe.builders";

export const usAssets: AssetSeed[] = [
  yahoo("us-ixic", "^IXIC", "纳斯达克综合指数", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-dji", "^DJI", "道琼斯工业指数", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-ndx", "^NDX", "纳斯达克 100", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-spy", "SPY", "S&P 500 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数"]),
  yahoo("us-vti", "VTI", "美国全市场 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数", "全市场"]),
  yahoo("us-qqq", "QQQ", "Nasdaq 100 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数"]),
  yahoo("us-dia", "DIA", "道琼斯 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数"]),
  yahoo("us-rsp", "RSP", "标普 500 等权 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数", "等权"]),
  yahoo("us-iwm", "IWM", "Russell 2000 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "小盘"]),
  yahoo("us-acwi", "ACWI", "全球股票 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "broad-index", ["ETF", "全球股票"]),
  yahoo("us-efa", "EFA", "发达市场股票 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "海外", "发达市场"]),
  yahoo("us-eem", "EEM", "新兴市场股票 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "海外", "新兴市场"]),
  yahoo("us-vea", "VEA", "发达市场 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "海外", "发达市场"]),
  yahoo("us-vwo", "VWO", "新兴市场 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "海外", "新兴市场"]),
  yahoo("us-xlk", "XLK", "美股科技行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["科技", "行业基金"]),
  yahoo("us-xlf", "XLF", "美股金融行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["金融", "行业基金"]),
  yahoo("us-xle", "XLE", "美股能源行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["能源", "行业基金"]),
  yahoo("us-xlv", "XLV", "美股医疗行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["医疗", "行业基金"]),
  yahoo("us-xly", "XLY", "美股可选消费 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["可选消费", "行业基金"]),
  yahoo("us-xlp", "XLP", "美股必需消费 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["必需消费", "行业基金"]),
  yahoo("us-xli", "XLI", "美股工业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["工业", "行业基金"]),
  yahoo("us-xlu", "XLU", "美股公用事业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["公用事业", "行业基金"]),
  yahoo("us-xlb", "XLB", "美股材料 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["材料", "行业基金"]),
  yahoo("us-xlc", "XLC", "美股通信服务 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["通信服务", "行业基金"]),
  yahoo("us-xlre", "XLRE", "美股房地产 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["房地产", "行业基金"]),
  yahoo("us-vnq", "VNQ", "美国 REITs ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["房地产", "REITs"]),
  yahoo("us-aapl", "AAPL", "Apple", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "科技"]),
  yahoo("us-msft", "MSFT", "Microsoft", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "科技"]),
  yahoo("us-nvda", "NVDA", "NVIDIA", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "AI"]),
  yahoo("us-tsla", "TSLA", "Tesla", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "新能源"]),
  yahoo("us-amzn", "AMZN", "Amazon", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "消费"]),
  yahoo("us-meta", "META", "Meta Platforms", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "互联网"]),
  yahoo("us-googl", "GOOGL", "Alphabet", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "互联网"]),
];
