import type { AssetSummary } from "@gold-insights/market-domain";

type AssetSeed = AssetSummary & { parentId?: string | null };

const node = (id: string, name: string, parentId: string | null, market: string, tags: string[] = []): AssetSeed => ({
  id,
  symbol: id.toUpperCase(),
  name,
  assetType: "index",
  market,
  exchange: "local",
  currency: "",
  universe: "global",
  level: parentId === null ? "asset-class" : "market",
  parentId,
  dataSource: "yahoo",
  vendorSymbol: id.toUpperCase(),
  tags
});

const yahoo = (
  id: string,
  symbol: string,
  name: string,
  assetType: AssetSummary["assetType"],
  market: string,
  exchange: string,
  currency: string,
  parentId: string,
  level: AssetSummary["level"],
  tags: string[] = []
): AssetSeed => ({
  id,
  symbol,
  name,
  assetType,
  market,
  exchange,
  currency,
  universe: "global",
  level,
  parentId,
  dataSource: "yahoo",
  vendorSymbol: symbol,
  tags
});

const eastmoneyFund = (id: string, code: string, name: string, tags: string[] = []): AssetSeed => ({
  id,
  symbol: code,
  name,
  assetType: "fund",
  market: "基金",
  exchange: "东方财富基金",
  currency: "CNY",
  universe: "global",
  level: "instrument",
  parentId: "market-cn-mutual-fund",
  dataSource: "eastmoney",
  vendorSymbol: code,
  tags: ["场外基金", ...tags]
});

const binance = (id: string, symbol: string, name: string, tags: string[] = []): AssetSeed => ({
  id,
  symbol,
  name,
  assetType: "crypto",
  market: "加密",
  exchange: "Yahoo Crypto",
  currency: "USD",
  universe: "global",
  level: "instrument",
  parentId: "market-crypto",
  dataSource: "yahoo",
  vendorSymbol: `${symbol.split("/")[0]}-USD`,
  tags
});

export const assetUniverse: AssetSummary[] = [
  node("asset-equity", "股票", null, "股票"),
  node("asset-fund", "基金/ETF", null, "基金"),
  node("asset-commodity", "商品", null, "商品"),
  node("asset-rates", "债券与利率", null, "债券"),
  node("asset-fx", "外汇", null, "外汇"),
  node("asset-crypto", "加密", null, "加密"),
  node("asset-macro", "宏观代理", null, "宏观"),
  node("market-us-equity", "美股", "asset-equity", "美股"),
  node("market-a-share", "中国 A 股", "asset-equity", "A 股"),
  node("market-hk-equity", "港股", "asset-equity", "港股"),
  node("market-us-fund", "美股基金/ETF", "asset-fund", "美股"),
  node("market-cn-fund", "A 股基金/ETF", "asset-fund", "A 股"),
  node("market-cn-mutual-fund", "场外基金", "asset-fund", "基金"),
  node("market-hk-fund", "港股基金/ETF", "asset-fund", "港股"),
  node("market-commodity-fund", "商品基金/ETF", "asset-fund", "商品"),
  node("market-commodity", "商品期货", "asset-commodity", "商品"),
  node("market-rates", "债券与利率", "asset-rates", "债券"),
  node("market-fx", "外汇", "asset-fx", "外汇"),
  node("market-crypto", "加密资产", "asset-crypto", "加密"),
  node("market-macro", "宏观代理指标", "asset-macro", "宏观"),

  yahoo("us-ixic", "^IXIC", "纳斯达克综合指数", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-dji", "^DJI", "道琼斯工业指数", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-ndx", "^NDX", "纳斯达克 100", "index", "美股", "Yahoo", "USD", "market-us-equity", "broad-index", ["宽基指数"]),
  yahoo("us-spy", "SPY", "S&P 500 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数"]),
  yahoo("us-qqq", "QQQ", "Nasdaq 100 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "broad-index", ["ETF", "宽基指数"]),
  yahoo("us-iwm", "IWM", "Russell 2000 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "broad-index", ["ETF", "小盘"]),
  yahoo("us-xlk", "XLK", "美股科技行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["科技", "行业基金"]),
  yahoo("us-xlf", "XLF", "美股金融行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["金融", "行业基金"]),
  yahoo("us-xle", "XLE", "美股能源行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["能源", "行业基金"]),
  yahoo("us-xlv", "XLV", "美股医疗行业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["医疗", "行业基金"]),
  yahoo("us-aapl", "AAPL", "Apple", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "科技"]),
  yahoo("us-msft", "MSFT", "Microsoft", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "科技"]),
  yahoo("us-nvda", "NVDA", "NVIDIA", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "AI"]),
  yahoo("us-tsla", "TSLA", "Tesla", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "新能源"]),
  yahoo("us-amzn", "AMZN", "Amazon", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "消费"]),
  yahoo("us-meta", "META", "Meta Platforms", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "互联网"]),
  yahoo("us-googl", "GOOGL", "Alphabet", "equity", "美股", "Nasdaq", "USD", "market-us-equity", "company", ["重点公司", "互联网"]),

  yahoo("cn-sse", "000001.SS", "上证指数", "index", "A 股", "SSE", "CNY", "market-a-share", "broad-index", ["宽基指数"]),
  yahoo("cn-csi300", "000300.SS", "沪深 300", "index", "A 股", "SSE", "CNY", "market-a-share", "broad-index", ["宽基指数"]),
  yahoo("cn-szse", "399001.SZ", "深证成指", "index", "A 股", "SZSE", "CNY", "market-a-share", "broad-index", ["宽基指数"]),
  yahoo("cn-300etf", "510300.SS", "沪深 300 ETF", "fund", "A 股", "SSE", "CNY", "market-cn-fund", "broad-index", ["ETF"]),
  yahoo("cn-chip-512480", "512480.SS", "半导体 ETF", "fund", "A 股", "SSE", "CNY", "market-cn-fund", "sector-index", ["半导体", "行业基金"]),
  yahoo("cn-chip-512760", "512760.SS", "芯片 ETF", "fund", "A 股", "SSE", "CNY", "market-cn-fund", "sector-index", ["半导体", "行业基金"]),
  yahoo("cn-ai-515790", "515790.SS", "光伏/新能源 ETF", "fund", "A 股", "SSE", "CNY", "market-cn-fund", "theme-basket", ["主题篮子", "行业基金"]),
  yahoo("cn-kweichow", "600519.SS", "贵州茅台", "equity", "A 股", "SSE", "CNY", "market-a-share", "company", ["重点公司", "消费"]),
  yahoo("cn-catl", "300750.SZ", "宁德时代", "equity", "A 股", "SZSE", "CNY", "market-a-share", "company", ["重点公司", "新能源"]),
  yahoo("cn-pingan", "601318.SS", "中国平安", "equity", "A 股", "SSE", "CNY", "market-a-share", "company", ["重点公司", "金融"]),
  yahoo("cn-cmb", "600036.SS", "招商银行", "equity", "A 股", "SSE", "CNY", "market-a-share", "company", ["重点公司", "金融"]),
  yahoo("cn-byd", "002594.SZ", "比亚迪", "equity", "A 股", "SZSE", "CNY", "market-a-share", "company", ["重点公司", "新能源"]),

  yahoo("hk-hsi", "^HSI", "恒生指数", "index", "港股", "HKEX", "HKD", "market-hk-equity", "broad-index", ["宽基指数"]),
  yahoo("hk-tracker", "2800.HK", "盈富基金", "fund", "港股", "HKEX", "HKD", "market-hk-fund", "broad-index", ["ETF", "指数基金"]),
  yahoo("hk-tencent", "0700.HK", "腾讯控股", "equity", "港股", "HKEX", "HKD", "market-hk-equity", "company", ["重点公司", "互联网"]),
  yahoo("hk-baba", "9988.HK", "阿里巴巴-W", "equity", "港股", "HKEX", "HKD", "market-hk-equity", "company", ["重点公司", "互联网"]),
  yahoo("hk-meituan", "3690.HK", "美团-W", "equity", "港股", "HKEX", "HKD", "market-hk-equity", "company", ["重点公司", "消费"]),

  yahoo("cmd-gold", "GC=F", "COMEX 黄金", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-silver", "SI=F", "COMEX 白银", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-copper", "HG=F", "COMEX 铜", "commodity", "商品", "COMEX", "USD", "market-commodity", "instrument", ["工业金属"]),
  yahoo("cmd-platinum", "PL=F", "NYMEX 铂金", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-palladium", "PA=F", "NYMEX 钯金", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["贵金属"]),
  yahoo("cmd-wti", "CL=F", "WTI 原油", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-brent", "BZ=F", "Brent 原油", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-gas", "NG=F", "天然气", "commodity", "商品", "NYMEX", "USD", "market-commodity", "instrument", ["能源"]),
  yahoo("cmd-corn", "ZC=F", "CBOT 玉米", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-wheat", "ZW=F", "CBOT 小麦", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-soybean", "ZS=F", "CBOT 大豆", "commodity", "商品", "CBOT", "USD", "market-commodity", "instrument", ["农产品"]),
  yahoo("cmd-coffee", "KC=F", "ICE 咖啡", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-sugar", "SB=F", "ICE 原糖", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-cotton", "CT=F", "ICE 棉花", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-cocoa", "CC=F", "ICE 可可", "commodity", "商品", "ICE", "USD", "market-commodity", "instrument", ["软商品"]),
  yahoo("cmd-live-cattle", "LE=F", "CME 活牛", "commodity", "商品", "CME", "USD", "market-commodity", "instrument", ["牲畜"]),
  yahoo("cmd-lean-hogs", "HE=F", "CME 瘦猪肉", "commodity", "商品", "CME", "USD", "market-commodity", "instrument", ["牲畜"]),
  yahoo("fund-gld", "GLD", "SPDR 黄金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-iau", "IAU", "iShares 黄金信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-gldm", "GLDM", "SPDR Mini 黄金信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "黄金"]),
  yahoo("fund-slv", "SLV", "iShares 白银信托", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "白银"]),
  yahoo("fund-pplt", "PPLT", "abrdn 铂金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "铂金"]),
  yahoo("fund-pall", "PALL", "abrdn 钯金 ETF", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "贵金属", "钯金"]),
  yahoo("fund-cper", "CPER", "United States 铜指数基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "工业金属", "铜"]),
  yahoo("fund-uso", "USO", "United States Oil Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "原油"]),
  yahoo("fund-ung", "UNG", "United States Natural Gas Fund", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "能源", "天然气"]),
  yahoo("fund-dba", "DBA", "Invesco 农产品基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "农业", "大宗商品"]),
  yahoo("fund-corn", "CORN", "Teucrium 玉米基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农业", "玉米"]),
  yahoo("fund-weat", "WEAT", "Teucrium 小麦基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农业", "小麦"]),
  yahoo("fund-soyb", "SOYB", "Teucrium 大豆基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "农业", "大豆"]),
  yahoo("fund-cane", "CANE", "Teucrium 糖基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "instrument", ["ETF", "软商品", "糖"]),
  yahoo("fund-dbc", "DBC", "Invesco 综合商品指数基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "综合商品"]),
  yahoo("fund-dbb", "DBB", "Invesco 基本金属基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "工业金属", "综合商品"]),
  yahoo("fund-gsg", "GSG", "iShares GSCI 商品基金", "fund", "商品", "NYSE Arca", "USD", "market-commodity-fund", "theme-basket", ["ETF", "综合商品"]),
  yahoo("fund-xme", "XME", "SPDR 金属矿业 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["ETF", "金属矿业", "周期"]),
  yahoo("fund-xop", "XOP", "SPDR 油气勘探 ETF", "fund", "美股", "NYSE Arca", "USD", "market-us-fund", "sector-index", ["ETF", "油气", "能源"]),
  yahoo("fund-soxx", "SOXX", "iShares 半导体 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "sector-index", ["ETF", "半导体", "科技"]),
  yahoo("fund-smh", "SMH", "VanEck 半导体 ETF", "fund", "美股", "Nasdaq", "USD", "market-us-fund", "sector-index", ["ETF", "半导体", "科技"]),
  eastmoneyFund("fund-cn-005827", "005827", "易方达蓝筹精选混合", ["混合型", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-161725", "161725", "招商中证白酒指数(LOF)", ["消费", "白酒", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-320007", "320007", "诺安成长混合A", ["半导体", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-003095", "003095", "中欧医疗健康混合A", ["医疗", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-002190", "002190", "农银新能源主题", ["新能源", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-000961", "000961", "天弘沪深300ETF联接", ["宽基", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-161005", "161005", "富国天惠成长混合", ["成长", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-260108", "260108", "景顺长城新兴成长混合", ["成长", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-110022", "110022", "易方达消费行业股票", ["消费", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-110020", "110020", "易方达沪深300ETF联接A", ["宽基", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-001475", "001475", "易方达国防军工混合A", ["军工", "主题基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-001875", "001875", "前海开源沪港深优势精选混合A", ["港股", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-001717", "001717", "工银前沿医疗股票A", ["医疗", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-000083", "000083", "汇添富消费行业混合", ["消费", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-000336", "000336", "农银研究精选混合", ["主动权益", "成长", "支付宝常见"]),
  eastmoneyFund("fund-cn-000248", "000248", "汇添富中证主要消费ETF联接A", ["消费", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-519674", "519674", "银河创新成长混合A", ["科技", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-163406", "163406", "兴全合润混合(LOF)", ["主动权益", "均衡", "支付宝常见"]),
  eastmoneyFund("fund-cn-163402", "163402", "兴全趋势投资混合(LOF)", ["主动权益", "均衡", "支付宝常见"]),
  eastmoneyFund("fund-cn-270023", "270023", "广发全球精选股票(QDII)人民币A", ["QDII", "海外", "支付宝常见"]),
  eastmoneyFund("fund-cn-000696", "000696", "汇添富环保行业股票", ["环保", "主题基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-001618", "001618", "天弘中证电子ETF联接C", ["电子", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-003834", "003834", "华夏能源革新股票A", ["新能源", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-004854", "004854", "广发中证全指汽车指数A", ["汽车", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-005669", "005669", "前海开源公用事业股票", ["公用事业", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-007119", "007119", "睿远成长价值混合A", ["成长", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-008888", "008888", "华夏国证半导体芯片ETF联接C", ["半导体", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-009341", "009341", "易方达均衡成长股票", ["成长", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-010347", "010347", "农银策略收益一年持有混合", ["主动权益", "持有期", "支付宝常见"]),
  eastmoneyFund("fund-cn-012414", "012414", "招商中证白酒指数(LOF)C", ["消费", "白酒", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-014736", "014736", "创金合信专精特新股票发起A", ["专精特新", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-162411", "162411", "华宝油气(LOF)A", ["QDII", "油气", "支付宝常见"]),
  eastmoneyFund("fund-cn-161903", "161903", "万家行业优选混合(LOF)", ["主动权益", "行业轮动", "支付宝常见"]),
  eastmoneyFund("fund-cn-160222", "160222", "国泰国证食品饮料行业(LOF)A", ["消费", "食品饮料", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-001838", "001838", "国投瑞银国家安全混合A", ["军工", "主题基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-000977", "000977", "长城环保主题混合A", ["环保", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-000051", "000051", "华夏沪深300ETF联接A", ["宽基", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-110026", "110026", "易方达创业板ETF联接A", ["创业板", "指数基金", "支付宝常见"]),
  eastmoneyFund("fund-cn-100032", "100032", "富国中证红利指数增强A", ["红利", "指数增强", "支付宝常见"]),
  eastmoneyFund("fund-cn-000311", "000311", "景顺长城沪深300指数增强A", ["宽基", "指数增强", "支付宝常见"]),
  eastmoneyFund("fund-cn-070032", "070032", "嘉实优化红利混合A", ["红利", "主动权益", "支付宝常见"]),
  eastmoneyFund("fund-cn-519688", "519688", "交银精选混合", ["主动权益", "均衡", "支付宝常见"]),
  eastmoneyFund("fund-cn-040008", "040008", "华安策略优选混合A", ["主动权益", "均衡", "支付宝常见"]),
  eastmoneyFund("fund-cn-519069", "519069", "汇添富价值精选混合A", ["价值", "主动权益", "支付宝常见"]),

  yahoo("rate-tlt", "TLT", "20Y+ 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("rate-ief", "IEF", "7-10Y 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("rate-shy", "SHY", "1-3Y 美债 ETF", "fund", "债券", "NYSE Arca", "USD", "market-rates", "instrument", ["债券", "ETF"]),
  yahoo("macro-tnx", "^TNX", "美国 10Y 利率", "macro", "宏观", "Yahoo", "%", "market-macro", "macro-indicator", ["利率"]),
  yahoo("macro-vix", "^VIX", "VIX 波动率指数", "macro", "宏观", "CBOE", "USD", "market-macro", "macro-indicator", ["风险"]),
  yahoo("fx-dxy", "DX-Y.NYB", "美元指数", "macro", "外汇", "ICE", "USD", "market-fx", "instrument", ["美元"]),
  yahoo("fx-eurusd", "EURUSD=X", "欧元兑美元", "macro", "外汇", "Yahoo", "USD", "market-fx", "instrument", ["外汇"]),
  yahoo("fx-usdjpy", "JPY=X", "美元兑日元", "macro", "外汇", "Yahoo", "JPY", "market-fx", "instrument", ["外汇"]),
  yahoo("fx-usdcny", "USDCNY=X", "美元兑人民币", "macro", "外汇", "Yahoo", "CNY", "market-fx", "instrument", ["外汇"]),

  binance("btcusdt", "BTC/USDT", "Bitcoin", ["加密", "重点资产"]),
  binance("ethusdt", "ETH/USDT", "Ethereum", ["加密", "重点资产"]),
  binance("bnbusdt", "BNB/USDT", "BNB", ["加密"]),
  binance("solusdt", "SOL/USDT", "Solana", ["加密"]),
  binance("xrpusdt", "XRP/USDT", "XRP", ["加密"]),
  binance("dogeusdt", "DOGE/USDT", "Dogecoin", ["加密"]),
  binance("adausdt", "ADA/USDT", "Cardano", ["加密"]),
  binance("linkusdt", "LINK/USDT", "Chainlink", ["加密"])
];

export const tradableAssetUniverse = assetUniverse.filter((asset) => asset.level !== "asset-class" && asset.level !== "market");
